"""Generate a post's Watch widget (row markup + viewer + both <script>
blocks) from its already-authored video config, instead of hand-typing
the JS every time.

Local dev tool only - not part of the deployed Jekyll site. The video
config (scripts/video-configs/<slug>.py, see docs/production-pipeline.md
section 4) is the single source of truth for slides/schedule; this
script translates it into the JS shape the live widget needs (CSS
"50% 50%" pan strings instead of Python (0.5, 0.5) tuples, an
imageSchedule array instead of SCHEDULE tuples, etc.) and pastes in the
real sentence timings from TIMING_JSON verbatim. This removes the two
most common hand-authoring bugs from docs/production-pipeline.md's
gotchas list: the watchAudio/audio scope bug (always generated
correctly here) and Python/JS values drifting out of sync (there's only
one source now).

Does NOT require a YouTube/Shorts URL to run - a post's video is
usually rendered and reviewed before it's uploaded, so those URLs often
don't exist yet at Watch-widget-authoring time. Pass --youtube-url/
--shorts-url once they do; omit either (or both) and the row simply
gets Listen+Watch only, with a note printed to re-run once the URL(s)
exist. Re-running is always safe (idempotent) - the generated block is
wrapped in HTML comment markers so a second run replaces it in place
rather than duplicating it.

Chart and route-walk slides (see CLAUDE.md's Charts / Route animations
sections) are NOT auto-generated - their JS is structurally different
from a plain image slide (an SVG chart/route, not a background-image
div) and needs its own hand-authored buildChartSlide()/route-walk block
copied from an existing post with one. Any such slide in the config
gets a loud placeholder comment in the generated output instead of
being silently wrong.

Usage:
    python scripts/build_watch_widget.py \\
        _posts/<file>.md \\
        scripts/video-configs/<slug>.py \\
        [--youtube-url https://youtu.be/...] \\
        [--shorts-url https://youtube.com/shorts/...]
"""
import argparse
import hashlib
import importlib.util
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BACK_LINK_LINE = "[← Back to all posts](/)"
MARKER_BEGIN = "<!-- WATCH-WIDGET:BEGIN (generated by scripts/build_watch_widget.py - do not hand-edit between these markers, re-run the script instead) -->"
MARKER_END = "<!-- WATCH-WIDGET:END -->"


def load_config(config_path: Path):
    spec = importlib.util.spec_from_file_location(config_path.stem, config_path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def fmt_pct(fraction: float) -> str:
    """0.45 -> "45%", 0.671 -> "67.1%" - matches the CSS background-position
    percentage strings the live widget's JS expects (never Python's
    0-1 float tuples, which are for the PIL renderer only)."""
    pct = fraction * 100
    return f"{pct:g}%"


def js_pan(pan: tuple) -> str:
    return f'"{fmt_pct(pan[0])} {fmt_pct(pan[1])}"'


def audio_web_path(cfg) -> str:
    """The <audio> tag's web-facing src, derived from TIMING_JSON's own
    basename - NOT from the slug/config filename. Most posts' audio
    happens to share the config's slug, but a few (e.g. a post that was
    A/B-tested between TTS engines) keep a differently-suffixed filename
    as canonical (jalan-payoh-lai-kangkar-montfort-nativity-church's
    real audio is ...-kokoro.mp3, not the bare slug). Deriving from
    TIMING_JSON matches watch_video_lib.py's render() and guarantees the
    widget's audio always matches the sentence timings it's driven by -
    the two can never legitimately point at different files.

    Pure string manipulation, deliberately NOT pathlib.Path - this is a
    web URL, always forward-slashed, and Path() on Windows renders with
    backslashes (a real bug caught by the diff-audit: it produced
    "/audio\\foo.mp3" instead of "/audio/foo.mp3")."""
    tj = cfg.TIMING_JSON
    base = tj[: -len(".timing.json")] if tj.endswith(".timing.json") else tj.rsplit(".", 1)[0]
    return "/" + base + ".mp3"


def gradient_id(slug: str) -> str:
    """A per-post-unique SVG gradient id for the Shorts icon - collisions
    only matter if two posts' widgets ever render in the same DOM (not
    currently possible on this site), but the convention costs nothing."""
    words = re.sub(r"[^a-zA-Z0-9]", " ", slug).split()
    camel = "".join(w.capitalize() for w in words[:3])
    digest = hashlib.md5(slug.encode("utf-8")).hexdigest()[:4]
    return f"shortsGrad{camel}{digest}"


def build_slides_js(cfg, images_by_key: dict) -> tuple[list[str], int]:
    """Returns (lines, manual_count). Each SLIDES entry with an "img" key
    becomes a real { src: KEY, ... } JS object; anything else (chart,
    route-walk) becomes a flagged placeholder that still parses as valid
    JS (falls back to the post's own hero image) so the file doesn't
    break, but is unmistakably not the real slide."""
    lines = []
    manual_count = 0
    hero_key = next(iter(images_by_key), None)
    for i, slide in enumerate(cfg.SLIDES):
        key = slide.get("img")
        if key is None:
            manual_count += 1
            slide_type = slide.get("type", "unknown")
            comment = (f'/* MANUAL: slide {i} is type "{slide_type}" in the video config - '
                       f'auto-generation only covers cover/letterbox. Hand-author this slide '
                       f"per CLAUDE.md's Charts/Route animations section, copying the pattern "
                       f"from an existing post with one. Placeholder below just reuses the "
                       f"hero image so the widget still loads. */")
            lines.append(comment)
            lines.append(
                f'{{ src: {hero_key}, type: "cover", zoom: [1, 1, 1], '
                f'pan: ["50% 50%", "50% 50%", "50% 50%"], ease: "linear" }},'
            )
            continue
        zoom = json.dumps(slide["zoom"])
        pans = ", ".join(js_pan(p) for p in slide["pan"])
        ease = slide.get("ease", "ease-in-out")
        lines.append(
            f'{{ src: {key}, type: "{slide["type"]}", zoom: {zoom}, pan: [{pans}], ease: "{ease}" }},'
        )
    return lines, manual_count


def build_row_markup(youtube_url: str | None, shorts_url: str | None, grad_id: str) -> str:
    parts = [
        '<div style="display: flex; gap: 2em; margin: 0.5em 0 1.5em 0; align-items: flex-end;">',
        '  <div id="listen-widget" role="button" tabindex="0" aria-label="Play audio narration of this post" style="display: inline-flex; flex-direction: column; align-items: center; cursor: pointer; gap: 0.2em; user-select: none;">',
        '    <span id="listen-icon" aria-hidden="true" style="display: inline-flex; align-items: center; justify-content: center; width: 2.1em; height: 2.1em; border-radius: 50%; border: 1px solid #888; font-size: 1.1em;">&#127911;</span>',
        '    <span style="font-size: 0.7em; text-transform: uppercase; letter-spacing: 0.05em; opacity: 0.75;">Listen</span>',
        "  </div>",
        '  <div id="watch-widget" role="button" tabindex="0" aria-label="Watch an animated version of this post" style="display: inline-flex; flex-direction: column; align-items: center; cursor: pointer; gap: 0.2em; user-select: none;">',
        '    <span aria-hidden="true" style="display: inline-flex; align-items: center; justify-content: center; width: 2.1em; height: 2.1em; border-radius: 50%; border: 1px solid #888; font-size: 1.1em;">&#127916;</span>',
        '    <span style="font-size: 0.7em; text-transform: uppercase; letter-spacing: 0.05em; opacity: 0.75;">Watch</span>',
        "  </div>",
    ]
    if youtube_url:
        parts += [
            f'  <a href="{youtube_url}" target="_blank" rel="noopener" aria-label="Watch this story as a video on YouTube" style="display: inline-flex; flex-direction: column; align-items: center; gap: 0.2em; text-decoration: none; color: inherit;">',
            '    <span aria-hidden="true" style="display: inline-flex; align-items: center; justify-content: center; width: 2.4em; height: 2.4em; border-radius: 50%; border: 1px solid #888;">',
            '      <svg width="1.4em" height="1.4em" viewBox="0 0 24 24" aria-hidden="true"><rect x="1" y="4" width="22" height="16" rx="5" fill="#FF0000"/><path d="M10 8.5l6 3.5-6 3.5z" fill="#fff"/></svg>',
            "    </span>",
            '    <span style="font-size: 0.7em; text-transform: uppercase; letter-spacing: 0.05em; opacity: 0.75;">YouTube</span>',
            "  </a>",
        ]
    if shorts_url:
        parts += [
            f'  <a href="{shorts_url}" target="_blank" rel="noopener" aria-label="Watch a short version of this story on YouTube Shorts" style="display: inline-flex; flex-direction: column; align-items: center; gap: 0.2em; text-decoration: none; color: inherit;">',
            '    <span aria-hidden="true" style="display: inline-flex; align-items: center; justify-content: center; width: 2.4em; height: 2.4em; border-radius: 50%; border: 1px solid #888;">',
            '      <svg width="1.4em" height="1.4em" viewBox="0 0 24 24" aria-hidden="true">',
            "        <defs>",
            f'          <linearGradient id="{grad_id}" x1="0%" y1="0%" x2="100%" y2="100%">',
            '            <stop offset="0%" stop-color="#FF0000"/>',
            '            <stop offset="100%" stop-color="#FF4E8B"/>',
            "          </linearGradient>",
            "        </defs>",
            f'        <rect x="1" y="1" width="22" height="22" rx="7" fill="url(#{grad_id})"/>',
            '        <path d="M13 6 L7.5 13.5 H11.5 L10.5 18 L16.5 10 H12.5 Z" fill="#fff"/>',
            "      </svg>",
            "    </span>",
            '    <span style="font-size: 0.7em; text-transform: uppercase; letter-spacing: 0.05em; opacity: 0.75;">Shorts</span>',
            "  </a>",
        ]
    parts.append("</div>")
    return "\n".join(parts)


LISTEN_SCRIPT = """<script>
(function () {
  var widget = document.getElementById('listen-widget');
  var icon = document.getElementById('listen-icon');
  var audio = document.getElementById('listen-audio');

  function setIcon(playing) {
    icon.innerHTML = playing ? '&#10074;&#10074;' : '&#127911;';
  }
  function toggle() {
    if (audio.paused) { audio.play(); } else { audio.pause(); }
  }

  widget.addEventListener('click', toggle);
  widget.addEventListener('keydown', function (e) {
    if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); toggle(); }
  });
  audio.addEventListener('play', function () { setIcon(true); });
  audio.addEventListener('pause', function () { setIcon(false); });
  audio.addEventListener('ended', function () { setIcon(false); });
})();
</script>"""

VIEWER_MARKUP = """<div id="watch-viewer" style="position: fixed; inset: 0; background: #000; z-index: 9999; display: none;">
  <div id="watch-stage" style="position: absolute; inset: 0; overflow: hidden;"></div>
  <div style="position: absolute; left: 0; right: 0; bottom: 12%; text-align: center; padding: 0 5%; z-index: 2;">
    <span id="watch-caption" style="display: inline-block; background: rgba(0,0,0,0.55); color: #fff; font-size: 1.3em; font-weight: 600; padding: 0.5em 0.8em; border-radius: 4px; max-width: 700px;"></span>
  </div>
  <button id="watch-close" aria-label="Close" style="position: absolute; top: 1em; right: 1.2em; color: #fff; font-size: 1.6em; cursor: pointer; background: none; border: none; z-index: 2;">&times;</button>
  <div style="position: absolute; bottom: 0; left: 0; right: 0; padding: 1em 1.5em; display: flex; align-items: center; gap: 1em; background: linear-gradient(transparent, rgba(0,0,0,0.6)); z-index: 2;">
    <button id="watch-play" aria-label="Play/Pause" style="background: none; border: none; color: #fff; font-size: 1.4em; cursor: pointer; line-height: 1; padding: 0.2em;">&#10074;&#10074;</button>
    <div id="watch-progress" style="flex: 1; height: 4px; background: rgba(255,255,255,0.25); border-radius: 2px; overflow: hidden; cursor: pointer;">
      <div id="watch-progress-fill" style="height: 100%; width: 0%; background: #fff;"></div>
    </div>
    <span id="watch-time" style="color: #fff; font-size: 0.85em; font-variant-numeric: tabular-nums; opacity: 0.8;">0:00 / 0:00</span>
  </div>
</div>"""

# The caption chunker + update/event-wiring logic below is fixed across
# every post (only the data at the top - IMAGE vars, slides,
# sentences, imageSchedule, TOTAL_DURATION - varies), copied verbatim
# from docs/production-pipeline.md section 3's skeleton.
WATCH_SCRIPT_TAIL = """
  var MAX_CHARS = 100;
  function splitLongSentence(text, offset, duration) {
    if (text.length <= MAX_CHARS) return [{ text: text, offset_s: offset, duration_s: duration }];
    var parts = text.split(/(?<=[:;])\\s+/);
    var chunks = [];
    parts.forEach(function (p) {
      if (p.length <= MAX_CHARS) { chunks.push(p); return; }
      var words = p.split(' ');
      var cur = '';
      words.forEach(function (w) {
        if ((cur + ' ' + w).trim().length > MAX_CHARS) { chunks.push(cur.trim()); cur = w; }
        else { cur = (cur + ' ' + w).trim(); }
      });
      if (cur) chunks.push(cur.trim());
    });
    var totalChars = chunks.reduce(function (a, c) { return a + c.length; }, 0);
    var t = offset;
    return chunks.map(function (c) {
      var share = duration * (c.length / totalChars);
      var entry = { text: c, offset_s: t, duration_s: share };
      t += share;
      return entry;
    });
  }
  var captionChunks = [];
  sentences.forEach(function (s) {
    captionChunks = captionChunks.concat(splitLongSentence(s.text, s.offset_s, s.duration_s));
  });

  var slideDurations = imageSchedule.map(function (entry, i) {
    var next = imageSchedule[i + 1];
    return (next ? next.t : TOTAL_DURATION) - entry.t;
  });

  var viewer = document.getElementById('watch-viewer');
  var stage = document.getElementById('watch-stage');
  var captionEl = document.getElementById('watch-caption');
  var closeBtn = document.getElementById('watch-close');
  var playBtn = document.getElementById('watch-play');
  var progress = document.getElementById('watch-progress');
  var progressFill = document.getElementById('watch-progress-fill');
  var timeEl = document.getElementById('watch-time');
  var watchWidget = document.getElementById('watch-widget');

  // Separate Audio object from the Listen widget's <audio> element -
  // never share the `audio` variable across the two IIFEs (the #1
  // recurring bug in this pipeline's history, see
  // docs/production-pipeline.md section 13).
  var listenAudio = document.getElementById('listen-audio');
  var watchAudio = new Audio(listenAudio.querySelector('source').src);
  watchAudio.preload = 'none';

  var styleEl = document.createElement('style');
  document.head.appendChild(styleEl);

  var slideEls = slides.map(function (s, i) {
    var el = document.createElement('div');
    el.style.cssText = 'position:absolute;inset:0;opacity:0;transition:opacity 0.8s ease;';
    var ease = s.ease || 'linear';
    var dur = slideDurations[imageSchedule.findIndex(function (e) { return e.slide === i; })];

    if (s.type === 'letterbox') {
      var bg = document.createElement('div');
      bg.style.cssText = 'position:absolute;inset:-8%;background-size:cover;background-position:center;filter:blur(30px) brightness(0.55);background-image:url(\\'' + s.src + '\\');';
      bg.style.animation = 'kb' + i + ' ' + dur + 's ' + ease + ' forwards';
      var fg = document.createElement('div');
      fg.style.cssText = 'position:absolute;inset:6%;background-size:contain;background-position:center;background-repeat:no-repeat;background-image:url(\\'' + s.src + '\\');';
      el.appendChild(bg); el.appendChild(fg);
      el._animTargets = [bg];
    } else {
      var layer = document.createElement('div');
      layer.style.cssText = 'position:absolute;inset:-8%;background-size:cover;background-image:url(\\'' + s.src + '\\');';
      layer.style.animation = 'kb' + i + ' ' + dur + 's ' + ease + ' forwards';
      el.appendChild(layer);
      el._animTargets = [layer];
    }
    styleEl.textContent += '@keyframes kb' + i + ' { 0% { transform: scale(' + s.zoom[0] + '); background-position: ' + s.pan[0] + '; } 50% { transform: scale(' + s.zoom[1] + '); background-position: ' + s.pan[1] + '; } 100% { transform: scale(' + s.zoom[2] + '); background-position: ' + s.pan[2] + '; } }\\n';
    stage.appendChild(el);
    return el;
  });
  slides.forEach(function (s) { var img = new Image(); img.src = s.src; });

  var currentIndex = -1, currentSentenceIndex = -1;
  function fmtTime(t) {
    if (!isFinite(t)) return '0:00';
    var m = Math.floor(t / 60), s = Math.floor(t % 60);
    return m + ':' + (s < 10 ? '0' : '') + s;
  }
  function slideIndexForTime(t) {
    var idx = 0;
    for (var i = 0; i < imageSchedule.length; i++) { if (imageSchedule[i].t <= t) idx = imageSchedule[i].slide; else break; }
    return idx;
  }
  function sentenceIndexForTime(t) {
    var idx = 0;
    for (var i = 0; i < captionChunks.length; i++) { if (captionChunks[i].offset_s <= t) idx = i; else break; }
    return idx;
  }
  function updateForTime(t) {
    var sIdx = slideIndexForTime(t);
    if (sIdx !== currentIndex) {
      if (currentIndex >= 0) slideEls[currentIndex].style.opacity = '0';
      slideEls[sIdx].style.opacity = '1';
      currentIndex = sIdx;
    }
    var cIdx = sentenceIndexForTime(t);
    if (cIdx !== currentSentenceIndex) { captionEl.textContent = captionChunks[cIdx].text; currentSentenceIndex = cIdx; }
    var pct = Math.min(100, (t / TOTAL_DURATION) * 100);
    progressFill.style.width = pct + '%';
    timeEl.textContent = fmtTime(t) + ' / ' + fmtTime(TOTAL_DURATION);
  }
  function openViewer() {
    viewer.style.display = 'block';
    currentIndex = -1; currentSentenceIndex = -1;
    slideEls.forEach(function (el) { el.style.opacity = '0'; });
    watchAudio.currentTime = 0;
    updateForTime(0);
    watchAudio.play();
  }
  function closeViewer() { viewer.style.display = 'none'; watchAudio.pause(); }

  watchWidget.addEventListener('click', openViewer);
  watchWidget.addEventListener('keydown', function (e) { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); openViewer(); } });
  closeBtn.addEventListener('click', closeViewer);
  playBtn.addEventListener('click', function () { if (watchAudio.paused) watchAudio.play(); else watchAudio.pause(); });
  watchAudio.addEventListener('play', function () { playBtn.innerHTML = '&#10074;&#10074;'; });
  watchAudio.addEventListener('pause', function () { playBtn.innerHTML = '&#9654;'; });
  watchAudio.addEventListener('timeupdate', function () { updateForTime(watchAudio.currentTime); });
  watchAudio.addEventListener('ended', closeViewer);
  progress.addEventListener('click', function (e) {
    var rect = progress.getBoundingClientRect();
    var pct = (e.clientX - rect.left) / rect.width;
    watchAudio.currentTime = pct * TOTAL_DURATION;
  });
})();
</script>"""


JS_IDENTIFIER_RE = re.compile(r'^[A-Za-z_$][A-Za-z0-9_$]*$')


def build_watch_script(cfg, slug: str) -> tuple[str, int]:
    images_by_key = cfg.IMAGES
    for key in images_by_key:
        if not JS_IDENTIFIER_RE.match(key):
            # Every IMAGES key becomes a bare `var KEY = "url";` and a bare
            # `src: KEY` reference in the generated JS - not a valid target
            # for arbitrary strings the way a Python dict key is. Caught for
            # real: an auto-derived key starting with a digit ("2005...")
            # produced `var 2005... = ...;`, invalid JS that node --check
            # rejects outright. Fail loudly here rather than ship it.
            raise ValueError(
                f'IMAGES key {key!r} in {cfg.__name__} is not a valid JS identifier '
                f'(used as `var {key} = ...;` in the generated widget script) - '
                f'rename it to something like {"IMG_" + key if key else "IMG1"!r}.'
            )
    image_lines = [f'  var {key} = "{url}";' for key, url in images_by_key.items()]

    slide_lines, manual_count = build_slides_js(cfg, images_by_key)
    slides_block = "  var slides = [\n    " + "\n    ".join(slide_lines) + "\n  ];"

    timing_path = REPO_ROOT / cfg.TIMING_JSON
    sentences = json.loads(timing_path.read_text(encoding="utf-8"))
    sentences_line = "  var sentences = " + json.dumps(sentences, ensure_ascii=False) + ";"

    schedule_lines = ", ".join(f"{{ t: {t}, slide: {s} }}" for t, s in cfg.SCHEDULE)
    schedule_block = "  var imageSchedule = [\n    " + schedule_lines + "\n  ];"

    header = (
        "<script>\n(function () {\n"
        + "\n".join(image_lines) + "\n\n"
        + slides_block + "\n\n"
        + sentences_line + "\n\n"
        + schedule_block + "\n"
        + f"  var TOTAL_DURATION = {cfg.TOTAL_DURATION};\n"
    )
    return header + WATCH_SCRIPT_TAIL, manual_count


def find_existing_urls(text: str) -> tuple[str | None, str | None]:
    main_url, short_url = None, None
    for m in re.finditer(r'href="(https://(?:youtu\.be|(?:www\.)?youtube\.com)/[^"]+)"', text):
        url = m.group(1)
        if "/shorts/" in url:
            short_url = short_url or url
        else:
            main_url = main_url or url
    return main_url, short_url


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("post_path")
    ap.add_argument("config_path", help="scripts/video-configs/<slug>.py")
    ap.add_argument("--youtube-url", default=None)
    ap.add_argument("--shorts-url", default=None)
    args = ap.parse_args()

    post_path = Path(args.post_path)
    config_path = Path(args.config_path)
    slug = config_path.stem

    cfg = load_config(config_path)
    post_text = post_path.read_text(encoding="utf-8")

    # A URL already wired into the post (e.g. from a previous run) is
    # preserved even if this run doesn't pass --youtube-url/--shorts-url
    # again - re-running to pick up ONE new URL shouldn't blank the other.
    existing_youtube, existing_shorts = find_existing_urls(post_text)
    youtube_url = args.youtube_url or existing_youtube
    shorts_url = args.shorts_url or existing_shorts

    grad_id = gradient_id(slug)
    row_markup = build_row_markup(youtube_url, shorts_url, grad_id)
    watch_script, manual_count = build_watch_script(cfg, slug)

    block = "\n\n".join([
        MARKER_BEGIN,
        row_markup,
        (f'<audio id="listen-audio" preload="none" style="display: none;">\n'
         f'  <source src="{audio_web_path(cfg)}" type="audio/mpeg">\n'
         f'</audio>'),
        VIEWER_MARKUP,
        LISTEN_SCRIPT,
        watch_script,
        MARKER_END,
    ])

    has_markers = MARKER_BEGIN in post_text and MARKER_END in post_text
    has_watch_widget = 'id="watch-widget"' in post_text
    has_listen_widget = 'id="listen-widget"' in post_text

    if has_markers:
        pattern = re.compile(re.escape(MARKER_BEGIN) + r".*?" + re.escape(MARKER_END), re.DOTALL)
        # A callable replacement, not a raw string - `block` contains
        # literal backslashes (the JS caption chunker's \s+ regex), and
        # re.sub treats a *string* replacement's backslashes as
        # backreference escapes (\1 etc.), raising "bad escape \s" here.
        # A function is substituted verbatim with no such processing.
        new_text = pattern.sub(lambda _m: block, post_text, count=1)
        mode = "updated"
    elif has_watch_widget:
        print(f"ERROR: {post_path} already has a Watch widget that wasn't generated by this "
              f"script (no marker comments found), so it may carry hand-tuned data this script "
              f"can't tell apart from a stale duplicate. Refusing to touch it automatically - "
              f"remove the existing widget by hand first, or add the marker comments around it "
              f"yourself, then re-run.", file=sys.stderr)
        sys.exit(1)
    elif has_listen_widget:
        # Every post already got a bare Listen-only widget from the
        # site-wide rollout (scripts/insert_listen_widget.py) - this is
        # the expected, common starting point for adding a Watch widget,
        # not an unmanaged edge case. Safe to replace: that template's
        # shape is a single <div id="listen-widget">...</div> (with its
        # own nested <audio>) immediately followed by its one <script>
        # block - matched here from the div open to that script's close.
        bare_re = re.compile(r'<div id="listen-widget".*?</script>', re.DOTALL)
        m = bare_re.search(post_text)
        if not m:
            print(f"ERROR: found id=\"listen-widget\" in {post_path} but couldn't isolate its "
                  f"exact block boundaries (unexpected markup shape) - refusing to guess. Remove "
                  f"it by hand first, or add the marker comments around it yourself.",
                  file=sys.stderr)
            sys.exit(1)
        new_text = post_text[:m.start()] + block + post_text[m.end():]
        mode = "upgraded from Listen-only to"
    else:
        idx = post_text.find(BACK_LINK_LINE)
        if idx == -1:
            print(f"ERROR: no '{BACK_LINK_LINE}' line found in {post_path} - can't find where "
                  f"to insert the widget.", file=sys.stderr)
            sys.exit(1)
        insert_at = idx + len(BACK_LINK_LINE)
        new_text = post_text[:insert_at] + "\n\n" + block + post_text[insert_at:]
        mode = "inserted"

    post_path.write_text(new_text, encoding="utf-8")
    print(f"OK: {mode} Watch widget in {post_path}", file=sys.stderr)

    if manual_count:
        print(f"NOTE: {manual_count} slide(s) need manual authoring (chart/route-walk types "
              f"aren't auto-generated) - search the file for 'MANUAL:' comments.", file=sys.stderr)

    if not youtube_url or not shorts_url:
        missing = ", ".join(n for n, v in (("YouTube", youtube_url), ("Shorts", shorts_url)) if not v)
        print(f"NOTE: no {missing} URL yet - widget row omits {'that button' if ',' not in missing else 'those buttons'}. "
              f"Re-run this exact command with --youtube-url/--shorts-url once the video is "
              f"uploaded (see docs/production-pipeline.md sections 9-11) - it's safe to re-run, "
              f"the generated block gets replaced in place.", file=sys.stderr)


if __name__ == "__main__":
    main()
