"""Generate a post's Watch widget (row markup + viewer + both <script>
blocks) from its already-authored video config, instead of hand-typing
the JS every time.

Local dev tool only - not part of the deployed Jekyll site. The video
config (scripts/video-configs/<slug>.py, see docs/production-pipeline.md
section 4) is the single source of truth for slides/schedule; this
script translates it into the JS shape the live widget needs (CSS
"50% 50%" pan strings instead of Python (0.5, 0.5) tuples, an
imageSchedule array instead of SCHEDULE tuples, etc.) and pastes in the
real sentence timings from TIMING_JSON verbatim. This removes the two
most common hand-authoring bugs from docs/production-pipeline.md's
gotchas list: the watchAudio/audio scope bug (always generated
correctly here) and Python/JS values drifting out of sync (there's only
one source now).

Does NOT require a YouTube/Shorts URL to run - a post's video is
rendered and reviewed before it's uploaded, so those URLs never exist
yet at Watch-widget-authoring time (section 4). Omit them and the row
gets Listen+Watch only; the URLs get wired in later by re-running with
--youtube-url/--shorts-url (section 11). Re-running is always safe
(idempotent) - the generated block is wrapped in HTML comment markers
so a second run replaces it in place rather than duplicating it.

Chart slides ARE auto-generated: a `{"type": "chart", ...}` entry in
the config becomes a full `{ type: "chart", ... }` JS object plus the
generic `buildChartSlide()` SVG library, translated straight from the
config (including a small Python-format-string -> JS-formatter
converter for y_tick_format / value_format). A chart whose format
strings the converter doesn't recognise falls back to a loud MANUAL
placeholder rather than emitting broken JS. Route-walk slides are still
NOT auto-generated - their JS is more bespoke - and get the MANUAL
placeholder; hand-author those per CLAUDE.md's Route animations section.

Usage:
    python scripts/build_watch_widget.py \\
        _posts/<file>.md \\
        scripts/video-configs/<slug>.py \\
        [--youtube-url https://youtu.be/...] \\
        [--shorts-url https://youtube.com/shorts/...]
"""
import argparse
import hashlib
import importlib.util
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BACK_LINK_LINE = "[← Back to all posts](/)"
MARKER_BEGIN = "<!-- WATCH-WIDGET:BEGIN (generated by scripts/build_watch_widget.py - do not hand-edit between these markers, re-run the script instead) -->"
MARKER_END = "<!-- WATCH-WIDGET:END -->"


def load_config(config_path: Path):
    spec = importlib.util.spec_from_file_location(config_path.stem, config_path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def fmt_pct(fraction: float) -> str:
    """0.45 -> "45%", 0.671 -> "67.1%" - matches the CSS background-position
    percentage strings the live widget's JS expects (never Python's
    0-1 float tuples, which are for the PIL renderer only)."""
    pct = fraction * 100
    return f"{pct:g}%"


def js_pan(pan: tuple) -> str:
    return f'"{fmt_pct(pan[0])} {fmt_pct(pan[1])}"'


def audio_web_path(cfg) -> str:
    """The <audio> tag's web-facing src, derived from TIMING_JSON's own
    basename - NOT from the slug/config filename. Most posts' audio
    happens to share the config's slug, but a few (e.g. a post that was
    A/B-tested between TTS engines) keep a differently-suffixed filename
    as canonical (jalan-payoh-lai-kangkar-montfort-nativity-church's
    real audio is ...-kokoro.mp3, not the bare slug). Deriving from
    TIMING_JSON matches watch_video_lib.py's render() and guarantees the
    widget's audio always matches the sentence timings it's driven by -
    the two can never legitimately point at different files.

    Pure string manipulation, deliberately NOT pathlib.Path - this is a
    web URL, always forward-slashed, and Path() on Windows renders with
    backslashes (a real bug caught by the diff-audit: it produced
    "/audio\\foo.mp3" instead of "/audio/foo.mp3")."""
    tj = cfg.TIMING_JSON
    base = tj[: -len(".timing.json")] if tj.endswith(".timing.json") else tj.rsplit(".", 1)[0]
    return "/" + base + ".mp3"


def gradient_id(slug: str) -> str:
    """A per-post-unique SVG gradient id for the Shorts icon - collisions
    only matter if two posts' widgets ever render in the same DOM (not
    currently possible on this site), but the convention costs nothing."""
    words = re.sub(r"[^a-zA-Z0-9]", " ", slug).split()
    camel = "".join(w.capitalize() for w in words[:3])
    digest = hashlib.md5(slug.encode("utf-8")).hexdigest()[:4]
    return f"shortsGrad{camel}{digest}"


def build_slides_js(cfg, images_by_key: dict) -> tuple[list[str], int, bool]:
    """Returns (lines, manual_count, has_chart). Each SLIDES entry with an
    "img" key becomes a real { src: KEY, ... } JS object. A "chart" slide
    is translated to a full { type: "chart", ... } object (chart_slide_js)
    unless a format string can't be converted. Anything else still
    unhandled (route-walk, or an untranslatable chart) becomes a flagged
    placeholder that still parses as valid JS (falls back to the hero
    image) so the file doesn't break, but is unmistakably not the real
    slide."""
    lines = []
    manual_count = 0
    has_chart = False
    hero_key = next(iter(images_by_key), None)
    for i, slide in enumerate(cfg.SLIDES):
        key = slide.get("img")
        if key is None:
            slide_type = slide.get("type", "unknown")
            if slide_type == "chart":
                chart_js = chart_slide_js(slide)
                if chart_js is not None:
                    lines.append(chart_js)
                    has_chart = True
                    continue
            manual_count += 1
            why = ("its y_tick_format / value_format isn't one this script can "
                   "convert to JS" if slide_type == "chart"
                   else "auto-generation only covers cover/letterbox/chart")
            comment = (f'/* MANUAL: slide {i} is type "{slide_type}" in the video config - '
                       f"{why}. Hand-author this slide per CLAUDE.md's "
                       f"Charts/Route animations section, copying the pattern from an "
                       f"existing post with one. Placeholder below just reuses the hero "
                       f"image so the widget still loads. */")
            lines.append(comment)
            lines.append(
                f'{{ src: {hero_key}, type: "cover", zoom: [1, 1, 1], '
                f'pan: ["50% 50%", "50% 50%", "50% 50%"], ease: "linear" }},'
            )
            continue
        zoom = json.dumps(slide["zoom"])
        pans = ", ".join(js_pan(p) for p in slide["pan"])
        ease = slide.get("ease", "ease-in-out")
        lines.append(
            f'{{ src: {key}, type: "{slide["type"]}", zoom: {zoom}, pan: [{pans}], ease: "{ease}" }},'
        )
    return lines, manual_count, has_chart


def build_row_markup(youtube_url: str | None, shorts_url: str | None, grad_id: str) -> str:
    parts = [
        '<div style="display: flex; gap: 2em; margin: 0.5em 0 1.5em 0; align-items: flex-end;">',
        '  <div id="listen-widget" role="button" tabindex="0" aria-label="Play audio narration of this post" style="display: inline-flex; flex-direction: column; align-items: center; cursor: pointer; gap: 0.2em; user-select: none;">',
        '    <span id="listen-icon" aria-hidden="true" style="display: inline-flex; align-items: center; justify-content: center; width: 2.1em; height: 2.1em; border-radius: 50%; border: 1px solid #888; font-size: 1.1em;">&#127911;</span>',
        '    <span style="font-size: 0.7em; text-transform: uppercase; letter-spacing: 0.05em; opacity: 0.75;">Listen</span>',
        "  </div>",
        '  <div id="watch-widget" role="button" tabindex="0" aria-label="Watch an animated version of this post" style="display: inline-flex; flex-direction: column; align-items: center; cursor: pointer; gap: 0.2em; user-select: none;">',
        '    <span aria-hidden="true" style="display: inline-flex; align-items: center; justify-content: center; width: 2.1em; height: 2.1em; border-radius: 50%; border: 1px solid #888; font-size: 1.1em;">&#127916;</span>',
        '    <span style="font-size: 0.7em; text-transform: uppercase; letter-spacing: 0.05em; opacity: 0.75;">Watch</span>',
        "  </div>",
    ]
    if youtube_url:
        parts += [
            f'  <a href="{youtube_url}" target="_blank" rel="noopener" aria-label="Watch this story as a video on YouTube" style="display: inline-flex; flex-direction: column; align-items: center; gap: 0.2em; text-decoration: none; color: inherit;">',
            '    <span aria-hidden="true" style="display: inline-flex; align-items: center; justify-content: center; width: 2.4em; height: 2.4em; border-radius: 50%; border: 1px solid #888;">',
            '      <svg width="1.4em" height="1.4em" viewBox="0 0 24 24" aria-hidden="true"><rect x="1" y="4" width="22" height="16" rx="5" fill="#FF0000"/><path d="M10 8.5l6 3.5-6 3.5z" fill="#fff"/></svg>',
            "    </span>",
            '    <span style="font-size: 0.7em; text-transform: uppercase; letter-spacing: 0.05em; opacity: 0.75;">YouTube</span>',
            "  </a>",
        ]
    if shorts_url:
        parts += [
            f'  <a href="{shorts_url}" target="_blank" rel="noopener" aria-label="Watch a short version of this story on YouTube Shorts" style="display: inline-flex; flex-direction: column; align-items: center; gap: 0.2em; text-decoration: none; color: inherit;">',
            '    <span aria-hidden="true" style="display: inline-flex; align-items: center; justify-content: center; width: 2.4em; height: 2.4em; border-radius: 50%; border: 1px solid #888;">',
            '      <svg width="1.4em" height="1.4em" viewBox="0 0 24 24" aria-hidden="true">',
            "        <defs>",
            f'          <linearGradient id="{grad_id}" x1="0%" y1="0%" x2="100%" y2="100%">',
            '            <stop offset="0%" stop-color="#FF0000"/>',
            '            <stop offset="100%" stop-color="#FF4E8B"/>',
            "          </linearGradient>",
            "        </defs>",
            f'        <rect x="1" y="1" width="22" height="22" rx="7" fill="url(#{grad_id})"/>',
            '        <path d="M13 6 L7.5 13.5 H11.5 L10.5 18 L16.5 10 H12.5 Z" fill="#fff"/>',
            "      </svg>",
            "    </span>",
            '    <span style="font-size: 0.7em; text-transform: uppercase; letter-spacing: 0.05em; opacity: 0.75;">Shorts</span>',
            "  </a>",
        ]
    parts.append("</div>")
    return "\n".join(parts)


LISTEN_SCRIPT = """<script>
(function () {
  var widget = document.getElementById('listen-widget');
  var icon = document.getElementById('listen-icon');
  var audio = document.getElementById('listen-audio');

  function setIcon(playing) {
    icon.innerHTML = playing ? '&#10074;&#10074;' : '&#127911;';
  }
  function toggle() {
    if (audio.paused) { audio.play(); } else { audio.pause(); }
  }

  widget.addEventListener('click', toggle);
  widget.addEventListener('keydown', function (e) {
    if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); toggle(); }
  });
  audio.addEventListener('play', function () { setIcon(true); });
  audio.addEventListener('pause', function () { setIcon(false); });
  audio.addEventListener('ended', function () { setIcon(false); });
})();
</script>"""

VIEWER_MARKUP = """<div id="watch-viewer" style="position: fixed; inset: 0; background: #000; z-index: 9999; display: none;">
  <div id="watch-stage" style="position: absolute; inset: 0; overflow: hidden;"></div>
  <div style="position: absolute; left: 0; right: 0; bottom: 12%; text-align: center; padding: 0 5%; z-index: 2;">
    <span id="watch-caption" style="display: inline-block; background: rgba(0,0,0,0.55); color: #fff; font-size: 1.3em; font-weight: 600; padding: 0.5em 0.8em; border-radius: 4px; max-width: 700px;"></span>
  </div>
  <button id="watch-close" aria-label="Close" style="position: absolute; top: 1em; right: 1.2em; color: #fff; font-size: 1.6em; cursor: pointer; background: none; border: none; z-index: 2;">&times;</button>
  <div style="position: absolute; bottom: 0; left: 0; right: 0; padding: 1em 1.5em; display: flex; align-items: center; gap: 1em; background: linear-gradient(transparent, rgba(0,0,0,0.6)); z-index: 2;">
    <button id="watch-play" aria-label="Play/Pause" style="background: none; border: none; color: #fff; font-size: 1.4em; cursor: pointer; line-height: 1; padding: 0.2em;">&#10074;&#10074;</button>
    <div id="watch-progress" style="flex: 1; height: 4px; background: rgba(255,255,255,0.25); border-radius: 2px; overflow: hidden; cursor: pointer;">
      <div id="watch-progress-fill" style="height: 100%; width: 0%; background: #fff;"></div>
    </div>
    <span id="watch-time" style="color: #fff; font-size: 0.85em; font-variant-numeric: tabular-nums; opacity: 0.8;">0:00 / 0:00</span>
  </div>
</div>"""

# The caption chunker + update/event-wiring logic below is fixed across
# every post (only the data at the top - IMAGE vars, slides,
# sentences, imageSchedule, TOTAL_DURATION - varies), copied verbatim
# from docs/production-pipeline.md section 3's skeleton.
WATCH_SCRIPT_TAIL = """
  var MAX_CHARS = 100;
  function splitLongSentence(text, offset, duration) {
    if (text.length <= MAX_CHARS) return [{ text: text, offset_s: offset, duration_s: duration }];
    var parts = text.split(/(?<=[:;])\\s+/);
    var chunks = [];
    parts.forEach(function (p) {
      if (p.length <= MAX_CHARS) { chunks.push(p); return; }
      var words = p.split(' ');
      var cur = '';
      words.forEach(function (w) {
        if ((cur + ' ' + w).trim().length > MAX_CHARS) { chunks.push(cur.trim()); cur = w; }
        else { cur = (cur + ' ' + w).trim(); }
      });
      if (cur) chunks.push(cur.trim());
    });
    var totalChars = chunks.reduce(function (a, c) { return a + c.length; }, 0);
    var t = offset;
    return chunks.map(function (c) {
      var share = duration * (c.length / totalChars);
      var entry = { text: c, offset_s: t, duration_s: share };
      t += share;
      return entry;
    });
  }
  var captionChunks = [];
  sentences.forEach(function (s) {
    captionChunks = captionChunks.concat(splitLongSentence(s.text, s.offset_s, s.duration_s));
  });

  var slideDurations = imageSchedule.map(function (entry, i) {
    var next = imageSchedule[i + 1];
    return (next ? next.t : TOTAL_DURATION) - entry.t;
  });

__CHART_LIB__
  var viewer = document.getElementById('watch-viewer');
  var stage = document.getElementById('watch-stage');
  var captionEl = document.getElementById('watch-caption');
  var closeBtn = document.getElementById('watch-close');
  var playBtn = document.getElementById('watch-play');
  var progress = document.getElementById('watch-progress');
  var progressFill = document.getElementById('watch-progress-fill');
  var timeEl = document.getElementById('watch-time');
  var watchWidget = document.getElementById('watch-widget');

  // Separate Audio object from the Listen widget's <audio> element -
  // never share the `audio` variable across the two IIFEs (the #1
  // recurring bug in this pipeline's history, see
  // docs/production-pipeline.md section 13).
  var listenAudio = document.getElementById('listen-audio');
  var watchAudio = new Audio(listenAudio.querySelector('source').src);
  watchAudio.preload = 'none';

  var styleEl = document.createElement('style');
  document.head.appendChild(styleEl);

  var slideEls = slides.map(function (s, i) {
    var el = document.createElement('div');
    el.style.cssText = 'position:absolute;inset:0;opacity:0;transition:opacity 0.8s ease;';
    var ease = s.ease || 'linear';
    var dur = slideDurations[imageSchedule.findIndex(function (e) { return e.slide === i; })];

    if (s.type === 'chart') {
      var chart = buildChartSlide(s);
      el.appendChild(chart.svg);
      el._chartUpdate = chart.update;
    } else if (s.type === 'letterbox') {
      var bg = document.createElement('div');
      bg.style.cssText = 'position:absolute;inset:-8%;background-size:cover;background-position:center;filter:blur(30px) brightness(0.55);background-image:url(\\'' + s.src + '\\');';
      bg.style.animation = 'kb' + i + ' ' + dur + 's ' + ease + ' forwards';
      var fg = document.createElement('div');
      fg.style.cssText = 'position:absolute;inset:6%;background-size:contain;background-position:center;background-repeat:no-repeat;background-image:url(\\'' + s.src + '\\');';
      el.appendChild(bg); el.appendChild(fg);
      el._animTargets = [bg];
    } else {
      var layer = document.createElement('div');
      layer.style.cssText = 'position:absolute;inset:-8%;background-size:cover;background-image:url(\\'' + s.src + '\\');';
      layer.style.animation = 'kb' + i + ' ' + dur + 's ' + ease + ' forwards';
      el.appendChild(layer);
      el._animTargets = [layer];
    }
    if (s.type !== 'chart') {
      styleEl.textContent += '@keyframes kb' + i + ' { 0% { transform: scale(' + s.zoom[0] + '); background-position: ' + s.pan[0] + '; } 50% { transform: scale(' + s.zoom[1] + '); background-position: ' + s.pan[1] + '; } 100% { transform: scale(' + s.zoom[2] + '); background-position: ' + s.pan[2] + '; } }\\n';
    }
    stage.appendChild(el);
    return el;
  });
  slides.forEach(function (s) { if (s.src) { var img = new Image(); img.src = s.src; } });

  var currentIndex = -1, currentSentenceIndex = -1;
  function fmtTime(t) {
    if (!isFinite(t)) return '0:00';
    var m = Math.floor(t / 60), s = Math.floor(t % 60);
    return m + ':' + (s < 10 ? '0' : '') + s;
  }
  function slideIndexForTime(t) {
    var idx = 0;
    for (var i = 0; i < imageSchedule.length; i++) { if (imageSchedule[i].t <= t) idx = imageSchedule[i].slide; else break; }
    return idx;
  }
  function sentenceIndexForTime(t) {
    var idx = 0;
    for (var i = 0; i < captionChunks.length; i++) { if (captionChunks[i].offset_s <= t) idx = i; else break; }
    return idx;
  }
  function updateForTime(t) {
    var sIdx = slideIndexForTime(t);
    if (sIdx !== currentIndex) {
      if (currentIndex >= 0) slideEls[currentIndex].style.opacity = '0';
      slideEls[sIdx].style.opacity = '1';
      currentIndex = sIdx;
    }
    if (slideEls[sIdx]._chartUpdate) {
      var schedIdx = imageSchedule.findIndex(function (e) { return e.slide === sIdx; });
      var segStart = imageSchedule[schedIdx].t;
      var nextEntry = imageSchedule[schedIdx + 1];
      var segEnd = nextEntry ? nextEntry.t : TOTAL_DURATION;
      var chartProgress = Math.min(1, Math.max(0, (t - segStart) / Math.max(0.001, segEnd - segStart)));
      slideEls[sIdx]._chartUpdate(t, chartProgress);
    }
    var cIdx = sentenceIndexForTime(t);
    if (cIdx !== currentSentenceIndex) { captionEl.textContent = captionChunks[cIdx].text; currentSentenceIndex = cIdx; }
    var pct = Math.min(100, (t / TOTAL_DURATION) * 100);
    progressFill.style.width = pct + '%';
    timeEl.textContent = fmtTime(t) + ' / ' + fmtTime(TOTAL_DURATION);
  }
  function openViewer() {
    viewer.style.display = 'block';
    currentIndex = -1; currentSentenceIndex = -1;
    slideEls.forEach(function (el) { el.style.opacity = '0'; });
    watchAudio.currentTime = 0;
    updateForTime(0);
    watchAudio.play();
  }
  function closeViewer() { viewer.style.display = 'none'; watchAudio.pause(); }

  watchWidget.addEventListener('click', openViewer);
  watchWidget.addEventListener('keydown', function (e) { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); openViewer(); } });
  closeBtn.addEventListener('click', closeViewer);
  playBtn.addEventListener('click', function () { if (watchAudio.paused) watchAudio.play(); else watchAudio.pause(); });
  watchAudio.addEventListener('play', function () { playBtn.innerHTML = '&#10074;&#10074;'; });
  watchAudio.addEventListener('pause', function () { playBtn.innerHTML = '&#9654;'; });
  watchAudio.addEventListener('timeupdate', function () { updateForTime(watchAudio.currentTime); });
  watchAudio.addEventListener('ended', closeViewer);
  progress.addEventListener('click', function (e) {
    var rect = progress.getBoundingClientRect();
    var pct = (e.clientX - rect.left) / rect.width;
    watchAudio.currentTime = pct * TOTAL_DURATION;
  });
})();
</script>"""


# Generic chart-slide SVG library - inserted into the widget script only
# when a config has a "chart" slide. Mirrors compose_chart_frame() /
# _draw_chart_panel() in scripts/watch_video_lib.py so the live widget
# and the exported video animate identically. Has no per-post content;
# a chart slide's data/formats/checkpoints live on the { type: "chart" }
# object built by chart_slide_js(). `s.series2` adds a stacked second
# panel (both panels in the top ~63% so the caption never overlaps).
CHART_LIB_JS = """  var CHART_W = 1280, CHART_H = 720;
  var SVGNS = 'http://www.w3.org/2000/svg';
  function svgEl(tag, attrs) {
    var e = document.createElementNS(SVGNS, tag);
    for (var k in attrs) { e.setAttribute(k, attrs[k]); }
    return e;
  }

  function buildChartSlide(s) {
    var svg = svgEl('svg', { viewBox: '0 0 ' + CHART_W + ' ' + CHART_H, width: '100%', height: '100%', preserveAspectRatio: 'xMidYMid meet' });
    svg.style.cssText = 'position:absolute;inset:0;background:#1a1a19;';

    var left = CHART_W * 0.09, right = CHART_W * 0.95;
    var xMin = s.xRange[0], xMax = s.xRange[1];
    var FONT = 'system-ui,-apple-system,"Segoe UI",sans-serif';
    function sx(yr) { return left + (yr - xMin) / (xMax - xMin) * (right - left); }

    if (s.title) {
      var titleEl = svgEl('text', { x: left, y: CHART_H * 0.08, fill: '#fff', 'font-size': CHART_H * 0.032, 'font-weight': '600', 'font-family': FONT });
      titleEl.textContent = s.title;
      svg.appendChild(titleEl);
    }

    function piecewiseInterp(checkpoints, x) {
      if (x <= checkpoints[0][0]) return checkpoints[0][1];
      if (x >= checkpoints[checkpoints.length - 1][0]) return checkpoints[checkpoints.length - 1][1];
      for (var i = 0; i < checkpoints.length - 1; i++) {
        var x0 = checkpoints[i][0], y0 = checkpoints[i][1], x1 = checkpoints[i + 1][0], y1 = checkpoints[i + 1][1];
        if (x0 <= x && x <= x1) { var f = (x1 !== x0) ? (x - x0) / (x1 - x0) : 0; return y0 + (y1 - y0) * f; }
      }
      return checkpoints[checkpoints.length - 1][1];
    }
    function interpAt(data, year) {
      if (year <= data[0][0]) return data[0][1];
      if (year >= data[data.length - 1][0]) return data[data.length - 1][1];
      for (var i = 0; i < data.length - 1; i++) {
        var y0 = data[i][0], v0 = data[i][1], y1 = data[i + 1][0], v1 = data[i + 1][1];
        if (y0 <= year && year <= y1) { var f = (y1 !== y0) ? (year - y0) / (y1 - y0) : 0; return v0 + (v1 - v0) * f; }
      }
      return data[data.length - 1][1];
    }

    function makePanel(pdata, spec, pTop, pBot, drawXTicks, panelLabel) {
      var yMin = spec.yRange[0], yMax = spec.yRange[1];
      function sy(v) { return pTop + (yMax - v) / (yMax - yMin) * (pBot - pTop); }
      var yTickFormat = spec.yTickFormat || function (v) { return '$' + v; };
      var valueFormat = spec.valueFormat || function (v) { return '$' + Math.round(v) + ' / sqft'; };
      var step = spec.yTickStep || ((yMax <= 800) ? 100 : 200);
      for (var v = 0; v <= yMax; v += step) {
        var y = sy(v);
        svg.appendChild(svgEl('line', { x1: left, x2: right, y1: y, y2: y, stroke: v === 0 ? '#383835' : '#2c2c2a', 'stroke-width': 1 }));
        var lt = svgEl('text', { x: left - 10, y: y + 4, fill: '#898781', 'font-size': CHART_H * 0.022, 'text-anchor': 'end', 'font-family': FONT });
        lt.textContent = yTickFormat(v);
        svg.appendChild(lt);
      }
      if (drawXTicks) {
        for (var yr = xMin; yr <= xMax; yr += 5) {
          var xt = svgEl('text', { x: sx(yr), y: pBot + CHART_H * 0.045, fill: '#898781', 'font-size': CHART_H * 0.022, 'text-anchor': 'middle', 'font-family': FONT });
          xt.textContent = String(yr);
          svg.appendChild(xt);
        }
      }
      if (panelLabel) {
        var pl = svgEl('text', { x: left, y: pTop - CHART_H * 0.025, fill: '#c3c2b7', 'font-size': CHART_H * 0.02, 'font-family': FONT });
        pl.textContent = panelLabel;
        svg.appendChild(pl);
      }

      var d = pdata.map(function (p, i) { return (i === 0 ? 'M' : 'L') + sx(p[0]) + ',' + sy(p[1]); }).join(' ');
      var path = svgEl('path', {
        d: d, fill: 'none', stroke: '#3987e5', 'stroke-width': Math.max(2, CHART_H * 0.0035),
        'stroke-linejoin': 'round', 'stroke-linecap': 'round', 'pathLength': '1',
        'stroke-dasharray': '1', 'stroke-dashoffset': '1'
      });
      svg.appendChild(path);

      var annEls = (spec.annotations || []).map(function (a) {
        var ax = sx(a[0]), ay = sy(a[1]);
        var r = Math.max(3, CHART_H * 0.006);
        var g = svgEl('g', { opacity: 0 });
        g.appendChild(svgEl('circle', { cx: ax, cy: ay, r: r, fill: '#3987e5', stroke: '#1a1a19', 'stroke-width': 2 }));
        var ly = a[3] === 'below' ? ay + r + 14 : ay - r - 6;
        var lbl = svgEl('text', { x: ax, y: ly, fill: '#c3c2b7', 'font-size': CHART_H * 0.02, 'text-anchor': 'middle', 'font-family': FONT });
        lbl.textContent = a[2];
        g.appendChild(lbl);
        svg.appendChild(g);
        return { year: a[0], el: g };
      });

      var dot = svgEl('circle', { r: Math.max(4, CHART_H * 0.007), fill: '#3987e5', stroke: '#1a1a19', 'stroke-width': 2, opacity: 0 });
      svg.appendChild(dot);
      var valText = svgEl('text', { fill: '#fff', 'font-size': CHART_H * 0.026, 'font-weight': '600', 'font-family': FONT, opacity: 0 });
      svg.appendChild(valText);
      var yearText = svgEl('text', { fill: '#c3c2b7', 'font-size': CHART_H * 0.02, 'font-family': FONT, opacity: 0 });
      svg.appendChild(yearText);

      return function updatePanel(curYear, progress) {
        path.setAttribute('stroke-dashoffset', String(1 - progress));
        var curVal = interpAt(pdata, curYear);
        var ex = sx(curYear), ey = sy(curVal);
        dot.setAttribute('cx', ex); dot.setAttribute('cy', ey); dot.setAttribute('opacity', 1);
        var labelX = Math.min(ex + 14, right - CHART_W * 0.16);
        valText.setAttribute('x', labelX); valText.setAttribute('y', ey - CHART_H * 0.03);
        valText.textContent = valueFormat(curVal); valText.setAttribute('opacity', 1);
        yearText.setAttribute('x', labelX); yearText.setAttribute('y', ey - CHART_H * 0.005);
        yearText.textContent = String(Math.round(curYear)); yearText.setAttribute('opacity', 1);
        annEls.forEach(function (a) { a.el.setAttribute('opacity', curYear >= a.year - 0.01 ? 1 : 0); });
      };
    }

    var updaters;
    if (s.series2) {
      updaters = [
        makePanel(s.data, s, CHART_H * 0.15, CHART_H * 0.40, false, null),
        makePanel(s.series2.data, s.series2, CHART_H * 0.45, CHART_H * 0.60, true, s.series2.label)
      ];
    } else {
      updaters = [makePanel(s.data, s, CHART_H * 0.16, CHART_H * 0.82, true, null)];
    }

    function update(t, progress) {
      var curYear = s.yearCheckpoints ? piecewiseInterp(s.yearCheckpoints, t) : xMin + (xMax - xMin) * progress;
      updaters.forEach(function (u) { u(curYear, progress); });
    }

    return { svg: svg, update: update };
  }
"""


_CHART_FMT_RE = re.compile(r'^([^{}]*)\{:(,?)\.(\d+)f\}([^{}]*)$')


def py_fmt_to_js(fmt: str) -> str | None:
    """Translate a Python number format string (a chart slide's
    y_tick_format / value_format) to a JS `function (v) { return ...; }`.
    Handles the "[prefix]{:[,].Nf}[suffix]" shape the project's chart
    configs use ("${:.0f} / sqft", "{:,.0f}", "{:.2f} children per
    woman"). Returns None for anything else so the caller can fall back
    to a MANUAL placeholder rather than emit broken JS."""
    m = _CHART_FMT_RE.match(fmt)
    if not m:
        return None
    pre, grp, prec, post = m.group(1), m.group(2), int(m.group(3)), m.group(4)
    if grp == ",":
        num = (f"v.toLocaleString('en-US', {{minimumFractionDigits: {prec}, "
               f"maximumFractionDigits: {prec}}})")
    else:
        num = f"v.toFixed({prec})"
    expr = num
    if pre:
        expr = f"{json.dumps(pre)} + " + expr
    if post:
        expr = expr + f" + {json.dumps(post)}"
    return f"function (v) {{ return {expr}; }}"


def _chart_spec_fields(d: dict) -> dict | None:
    yt = py_fmt_to_js(d.get("y_tick_format", "${:.0f}"))
    vf = py_fmt_to_js(d.get("value_format", "${:.0f} / sqft"))
    if yt is None or vf is None:
        return None
    out = {
        "data": json.dumps([list(p) for p in d["data"]]),
        "yRange": json.dumps(list(d["y_range"])),
        "yTickFormat": yt,
        "valueFormat": vf,
    }
    if "y_tick_step" in d:
        out["yTickStep"] = str(d["y_tick_step"])
    if d.get("annotations"):
        out["annotations"] = json.dumps([list(a) for a in d["annotations"]], ensure_ascii=False)
    if d.get("label"):
        out["label"] = json.dumps(d["label"], ensure_ascii=False)
    return out


def chart_slide_js(slide: dict) -> str | None:
    """Build the `{ type: "chart", ... },` JS object for one chart slide,
    from the video config's chart-slide dict. Returns None if a format
    string can't be translated (caller emits a MANUAL placeholder)."""
    top = _chart_spec_fields(slide)
    if top is None:
        return None
    lines = ['type: "chart"', f'xRange: {json.dumps(list(slide["x_range"]))}']
    if slide.get("title"):
        lines.append(f'title: {json.dumps(slide["title"], ensure_ascii=False)}')
    lines += [f"{k}: {v}" for k, v in top.items()]
    if slide.get("year_checkpoints"):
        lines.append("yearCheckpoints: "
                     + json.dumps([list(c) for c in slide["year_checkpoints"]]))
    if "series2" in slide:
        s2 = _chart_spec_fields(slide["series2"])
        if s2 is None:
            return None
        lines.append("series2: { "
                     + ", ".join(f"{k}: {v}" for k, v in s2.items()) + " }")
    return "{\n      " + ",\n      ".join(lines) + "\n    },"


JS_IDENTIFIER_RE = re.compile(r'^[A-Za-z_$][A-Za-z0-9_$]*$')


def build_watch_script(cfg, slug: str) -> tuple[str, int, bool]:
    images_by_key = cfg.IMAGES
    for key in images_by_key:
        if not JS_IDENTIFIER_RE.match(key):
            # Every IMAGES key becomes a bare `var KEY = "url";` and a bare
            # `src: KEY` reference in the generated JS - not a valid target
            # for arbitrary strings the way a Python dict key is. Caught for
            # real: an auto-derived key starting with a digit ("2005...")
            # produced `var 2005... = ...;`, invalid JS that node --check
            # rejects outright. Fail loudly here rather than ship it.
            raise ValueError(
                f'IMAGES key {key!r} in {cfg.__name__} is not a valid JS identifier '
                f'(used as `var {key} = ...;` in the generated widget script) - '
                f'rename it to something like {"IMG_" + key if key else "IMG1"!r}.'
            )
    image_lines = [f'  var {key} = "{url}";' for key, url in images_by_key.items()]

    slide_lines, manual_count, has_chart = build_slides_js(cfg, images_by_key)
    slides_block = "  var slides = [\n    " + "\n    ".join(slide_lines) + "\n  ];"

    timing_path = REPO_ROOT / cfg.TIMING_JSON
    sentences = json.loads(timing_path.read_text(encoding="utf-8"))
    sentences_line = "  var sentences = " + json.dumps(sentences, ensure_ascii=False) + ";"

    schedule_lines = ", ".join(f"{{ t: {t}, slide: {s} }}" for t, s in cfg.SCHEDULE)
    schedule_block = "  var imageSchedule = [\n    " + schedule_lines + "\n  ];"

    header = (
        "<script>\n(function () {\n"
        + "\n".join(image_lines) + "\n\n"
        + slides_block + "\n\n"
        + sentences_line + "\n\n"
        + schedule_block + "\n"
        + f"  var TOTAL_DURATION = {cfg.TOTAL_DURATION};\n"
    )
    tail = WATCH_SCRIPT_TAIL.replace(
        "__CHART_LIB__\n", (CHART_LIB_JS + "\n") if has_chart else "")
    return header + tail, manual_count, has_chart


def find_existing_urls(text: str) -> tuple[str | None, str | None]:
    main_url, short_url = None, None
    for m in re.finditer(r'href="(https://(?:youtu\.be|(?:www\.)?youtube\.com)/[^"]+)"', text):
        url = m.group(1)
        if "/shorts/" in url:
            short_url = short_url or url
        else:
            main_url = main_url or url
    return main_url, short_url


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("post_path")
    ap.add_argument("config_path", help="scripts/video-configs/<slug>.py")
    ap.add_argument("--youtube-url", default=None)
    ap.add_argument("--shorts-url", default=None)
    args = ap.parse_args()

    post_path = Path(args.post_path)
    config_path = Path(args.config_path)
    slug = config_path.stem

    cfg = load_config(config_path)
    post_text = post_path.read_text(encoding="utf-8")

    # A URL already wired into the post (e.g. from a previous run) is
    # preserved even if this run doesn't pass --youtube-url/--shorts-url
    # again - re-running to pick up ONE new URL shouldn't blank the other.
    existing_youtube, existing_shorts = find_existing_urls(post_text)
    youtube_url = args.youtube_url or existing_youtube
    shorts_url = args.shorts_url or existing_shorts

    grad_id = gradient_id(slug)
    row_markup = build_row_markup(youtube_url, shorts_url, grad_id)
    watch_script, manual_count, _has_chart = build_watch_script(cfg, slug)

    block = "\n\n".join([
        MARKER_BEGIN,
        row_markup,
        (f'<audio id="listen-audio" preload="none" style="display: none;">\n'
         f'  <source src="{audio_web_path(cfg)}" type="audio/mpeg">\n'
         f'</audio>'),
        VIEWER_MARKUP,
        LISTEN_SCRIPT,
        watch_script,
        MARKER_END,
    ])

    has_markers = MARKER_BEGIN in post_text and MARKER_END in post_text
    has_watch_widget = 'id="watch-widget"' in post_text
    has_listen_widget = 'id="listen-widget"' in post_text

    if has_markers:
        pattern = re.compile(re.escape(MARKER_BEGIN) + r".*?" + re.escape(MARKER_END), re.DOTALL)
        # A callable replacement, not a raw string - `block` contains
        # literal backslashes (the JS caption chunker's \s+ regex), and
        # re.sub treats a *string* replacement's backslashes as
        # backreference escapes (\1 etc.), raising "bad escape \s" here.
        # A function is substituted verbatim with no such processing.
        new_text = pattern.sub(lambda _m: block, post_text, count=1)
        mode = "updated"
    elif has_watch_widget:
        print(f"ERROR: {post_path} already has a Watch widget that wasn't generated by this "
              f"script (no marker comments found), so it may carry hand-tuned data this script "
              f"can't tell apart from a stale duplicate. Refusing to touch it automatically - "
              f"remove the existing widget by hand first, or add the marker comments around it "
              f"yourself, then re-run.", file=sys.stderr)
        sys.exit(1)
    elif has_listen_widget:
        # Every post already got a bare Listen-only widget from the
        # site-wide rollout (scripts/insert_listen_widget.py) - this is
        # the expected, common starting point for adding a Watch widget,
        # not an unmanaged edge case. Safe to replace: that template's
        # shape is a single <div id="listen-widget">...</div> (with its
        # own nested <audio>) immediately followed by its one <script>
        # block - matched here from the div open to that script's close.
        bare_re = re.compile(r'<div id="listen-widget".*?</script>', re.DOTALL)
        m = bare_re.search(post_text)
        if not m:
            print(f"ERROR: found id=\"listen-widget\" in {post_path} but couldn't isolate its "
                  f"exact block boundaries (unexpected markup shape) - refusing to guess. Remove "
                  f"it by hand first, or add the marker comments around it yourself.",
                  file=sys.stderr)
            sys.exit(1)
        new_text = post_text[:m.start()] + block + post_text[m.end():]
        mode = "upgraded from Listen-only to"
    else:
        idx = post_text.find(BACK_LINK_LINE)
        if idx == -1:
            print(f"ERROR: no '{BACK_LINK_LINE}' line found in {post_path} - can't find where "
                  f"to insert the widget.", file=sys.stderr)
            sys.exit(1)
        insert_at = idx + len(BACK_LINK_LINE)
        new_text = post_text[:insert_at] + "\n\n" + block + post_text[insert_at:]
        mode = "inserted"

    post_path.write_text(new_text, encoding="utf-8")
    print(f"OK: {mode} Watch widget in {post_path}", file=sys.stderr)

    if manual_count:
        print(f"NOTE: {manual_count} slide(s) need manual authoring (route-walk, or a chart "
              f"whose format strings this script can't convert) - search the file for "
              f"'MANUAL:' comments.", file=sys.stderr)


if __name__ == "__main__":
    main()
